- Project.swift
- teamplan/Info.plist
- teamplan/Resources/Database/Coredata.xcdatamodeld/Coredata.xcdatamodel/contents
- teamplan/Resources/GoogleService-Info.plist
- teamplan/Sources/App/TeamPlanApp.swift
- teamplan/Sources/Object/User/UserDTO.swift
- teamplan/Sources/Object/User/UserObject.swift
- teamplan/Sources/Services/SignupService.swift
- teamplan/Sources/Services/User/UserServicesCoredata.swift
- teamplan/Sources/Services/User/UserServicesFirestore.swift
* **info.plist 업데이트**
* 팀계정 firebase 연결확인 
* UI Scene 관련 warning 메세지제거 
* **Object 추가**
* DB <-> Service : Object
* Service <-> View/ViewModel : DTO
* **Signup 기능추가**
* Coredata & Firestore 업로드 Service코드 추가
* Service 사용 Object & DTO 객체코드 추가 
* Signup Service코드 추가
* **Etc**
* 가독성을 위한 main app코드 변경
* Coredata 관련 xcdatamodel 파일 ./Resource/Database 추가
* 16.0 빌드버젼 고정을 위한 Project.swift 수정  
확인 후, 코멘트 부탁드려요!
> Add Signup Service & Etc

- teamplan/Sources/Services/ChallengeService.swift
- teamplan/Sources/Services/HomeService.swift
- teamplan/Sources/ViewModels/AuthenticationViewModel.swift
- teamplan/Sources/ViewModels/HomeViewModel.swift
- teamplan/Sources/Views/Authentication/LoginView.swift
- teamplan/Sources/Views/Home/HomeView.swift
- teamplan/Sources/Views/Home/MainTapView.swift
- teamplan/Sources/Views/Onboarding/IntroView.swift
close or resolve or fix(fixed, fixes) #{issue number}
Describe the major changes in your work 
* Change 1
* Description
* Change 2
* Description
Leave message for reviewers who will check this Pull request
> [Feat] 구글로그인 결과 분기처리

- teamplan/Sources/App/TeamPlanApp.swift
- teamplan/Sources/Extensions/Binding+Extension.swift
- teamplan/Sources/Services/SignupLoadingService.swift
- teamplan/Sources/Services/SignupService.swift
- teamplan/Sources/Util/Utilities.swift
- teamplan/Sources/ViewModels/AuthenticationViewModel.swift
- teamplan/Sources/ViewModels/HomeViewModel.swift
- teamplan/Sources/ViewModels/SignupViewModel.swift
- teamplan/Sources/Views/Authentication/LoginView.swift
- teamplan/Sources/Views/Home/HomeView.swift
- teamplan/Sources/Views/Loading/ActivityIndicator.swift
- teamplan/Sources/Views/Loading/LoadingView.swift
- teamplan/Sources/Views/Loading/LoadingView3.swift
- teamplan/Sources/Views/Signup/SignupView.swift
- LoadingIndicator 추가
- 로그인, 회원가입 작업 중
> [feat] 'LoadingIndicator' 추가 및 로그인, 회원가입 기능 구현 중

- teamplan/Resources/Storage/Coredata.xcdatamodeld/Coredata.xcdatamodel/contents
- teamplan/Sources/Object/Challenge/ChallengeDTO.swift
- teamplan/Sources/Object/Challenge/ChallengeObject.swift
- teamplan/Sources/Object/Log/AccessLog.swift
- teamplan/Sources/Object/Log/ChallengeLog.swift
- teamplan/Sources/Object/Statistics/StatisticsObject.swift
- teamplan/Sources/Object/User/UserDTO.swift
- teamplan/Sources/Object/User/UserObject.swift
- teamplan/Sources/Services/Challenge/ChallengeServicesCoredata.swift
- teamplan/Sources/Services/ChallengeService.swift
- teamplan/Sources/Services/HomeService.swift
- teamplan/Sources/Services/Log/AccessLogServicesCoredata.swift
- teamplan/Sources/Services/Log/AccessLogServicesFirestore.swift
- teamplan/Sources/Services/Log/ChallengeLogServicesCoredata.swift
- teamplan/Sources/Services/Log/ChallengeLogServicesFirestore.swift
- teamplan/Sources/Services/LoginLoadingService.swift
- teamplan/Sources/Services/SignupLoadingService.swift
- teamplan/Sources/Services/SignupService.swift
- teamplan/Sources/Services/Statistics/StatisticsServicesCoredata.swift
- teamplan/Sources/Services/Statistics/StatisticsServicesFirestore.swift
- teamplan/Sources/Services/User/UserServicesCoredata.swift
- teamplan/Sources/Services/User/UserServicesFirestore.swift
- teamplan/Sources/Util/Utilities.swift
* **'SignupLoadingService' 함수 타입변경**
* 'Result' => 'async/throws'
* **'SignupLoadingService' 에 사용되는 객체 리팩토링**
* 'User' 'Challenge' 'Statistics' 'AccessLog' 'ChallengeLog'
* async/throws 함수타입 추가
* 커스텀 Exception Handler 개편
* 'Result' 분기개선 
자세한 변경점은 commit 메세지 확인 부탁드립니다 :)
> [refact] 'SignupLoadingService' 리팩토링 및 기능추가

- teamplan/Sources/Object/Challenge/ChallengeDTO.swift
- teamplan/Sources/Object/Log/ChallengeLog.swift
- teamplan/Sources/Object/Project/ProjectDTO.swift
- teamplan/Sources/Object/Statistics/StatisticsDTO.swift
- teamplan/Sources/Object/User/UserPhrase.swift
- teamplan/Sources/Services/Challenge/ChallengeServicesCoredata.swift
- teamplan/Sources/Services/ChallengeService.swift
- teamplan/Sources/Services/HomeService.swift
- teamplan/Sources/Services/Log/ChallengeLogServicesCoredata.swift
- teamplan/Sources/Services/Log/ChallengeLogServicesFirestore.swift
- teamplan/Sources/Services/LoginLoadingService.swift
- teamplan/Sources/Services/Project/ProjectServicesCoredata.swift
- teamplan/Sources/Services/SignupLoadingService.swift
- teamplan/Sources/Services/Statistics/StatisticsCenter.swift
- teamplan/Sources/Services/Statistics/StatisticsServicesCoredata.swift
- teamplan/Sources/ViewModels/HomeViewModel.swift
* 'ChallengeService' & 관련 객체 리팩토링
* 구성 함수들을 기존 'result' 타입을 'async/throws' 타입으로 변경
* 연관 객체 (Statistics/ChallengeLog) 타입들도 일부 변경
* 사용중인 함수들은 유지
* 나의 도전과제 및 전체 도전과제 기능구현
* 사용자통계 갱신 및 도전과제 로그기록 추가    
* 'HomeService' 및 관련 객체 리팩토링
* 구성 함수들을 기존 'result' 타입을 'async/throws' 타입으로 변경
* 사용자 문구추가
* 나의 도전과제 파트는 도전과제에서 구현한 내용을 가져와 사용하는것으로 변경
* 자세한 내용은 Commit Message 탐조 부탁드립니다 :)
> [Refact] 'HomeService' & 'ChallengeService'

- teamplan/Sources/Object/Challenge/ChallengeDTO.swift
- teamplan/Sources/Services/ChallengeService.swift
- teamplan/Sources/ViewModels/HomeViewModel.swift
* ChallengeDTO
* Legacy 객체제거
* 누락되거나 기능추가로 인한 인자추가
* ChallengeDTO
* ChallengeRewardDTO 
* ChallengeService
* 도전과제 보상에 따른 물방울 갯수변경 기능추가   
* 관련 support 함수변경
자세한 내용은 commit 메세지 및 코드확인 부탁드립니다 :)
> [feat] Add missing function to 'ChallengeService' & 'ChallengeDTO'

- teamplan/Sources/Services/Log/AccessLogServicesFirestore.swift
- teamplan/Sources/Services/Statistics/StatisticsServicesFirestore.swift
- teamplan/Sources/Services/User/UserServicesCoredata.swift
- teamplan/Sources/ViewModels/AuthenticationViewModel.swift
- teamplan/Sources/Views/Authentication/LoginView.swift
- teamplan/Sources/Views/Onboarding/IntroView.swift
- teamplan/Sources/Views/Signup/SignupView.swift
Describe the major changes in your work 
1. 회원가입, 로그인 화면전환 수정
2. 회원가입 화면 로딩 인디케이터 추가
3. 회원가입 성공 시 메인화면으로 전환
> [refact] refact signup process 

- teamplan/Sources/Archive/LoginLoadingServiceOld.swift
- teamplan/Sources/Object/Log/AccessLog.swift
- teamplan/Sources/Object/Statistics/StatisticsDTO.swift
- teamplan/Sources/Object/User/UserDTO.swift
- teamplan/Sources/Services/Challenge/ChallengeServicesCoredata.swift
- teamplan/Sources/Services/ChallengeService.swift
- teamplan/Sources/Services/HomeService.swift
- teamplan/Sources/Services/Log/AccessLogServicesCoredata.swift
- teamplan/Sources/Services/Log/AccessLogServicesFirestore.swift
- teamplan/Sources/Services/Log/ChallengeLogServicesCoredata.swift
- teamplan/Sources/Services/Log/ChallengeLogServicesFirestore.swift
- teamplan/Sources/Services/LoginLoadingService.swift
- teamplan/Sources/Services/SignupLoadingService.swift
- teamplan/Sources/Services/SignupService.swift
- teamplan/Sources/Services/Statistics/StatisticsServicesCoredata.swift
- teamplan/Sources/Services/Statistics/StatisticsServicesFirestore.swift
- teamplan/Sources/Services/User/UserServicesCoredata.swift
- teamplan/Sources/Services/User/UserServicesFirestore.swift
- teamplan/Sources/Util/Utilities.swift
- teamplan/Sources/ViewModels/AuthenticationViewModel.swift
* **Storage(Coredata/Storage) 코드변경**
* 불필요한 비동기함수 제거
* Coredata 및 기능함수에서 비동기 모두 제거
* CRUD 함수 구조화
* 객체별 상이했던 코드구조 일원화   
* 불필요한 사용자 오류메세지 제거
* **'LoginLoadingService' 재구성**
* 'SignupLoadingService' 와 유사한 'executor' 도입
* 기존 'Result' 타입함수 제거
* 'async throws' or 'throws' 타입으로 재구성  
* **Etc**
* 리팩토링에 따른 연관코드 수정 
자세한 변경내용은 Commit Message 참고 부탁드립니다 👍
> [Refact] 'LoginLoadingService' & Storage Related & Etc

- teamplan/Sources/Services/Authentication/AuthGoogleServices.swift
- teamplan/Sources/Services/SignupService.swift
- teamplan/Sources/Util/UserDefaultManager.swift
- teamplan/Sources/ViewModels/AuthenticationViewModel.swift
- teamplan/Sources/ViewModels/HomeViewModel.swift
- teamplan/Sources/Views/Authentication/LoginView.swift
- teamplan/Sources/Views/Home/HomeView.swift
- teamplan/Sources/Views/Onboarding/IntroView.swift
- teamplan/Sources/Views/Signup/SignupView.swift
1. userDefaultManager추가 및 로그인, 회원가입 시 UserDefault에 identifier 저장
2. UserDefault에 저장된 identifier로 로그인 여부 확인
3. 로그인화면, 회원가입화면, 홈화면 화면 이동을 위한 mainViewState 추가
> [refact] refact introView and login logic

- teamplan/Sources/Services/ChallengeService.swift
- teamplan/Sources/ViewModels/AuthenticationViewModel.swift
- teamplan/Sources/ViewModels/HomeViewModel.swift
- teamplan/Sources/Views/Authentication/LoginView.swift
- teamplan/Sources/Views/Home/HomeView.swift
- teamplan/Sources/Views/Onboarding/IntroView.swift
1. 임시 로그아웃 기능 추가
2. 로그인이후 FireStore, Coredata 연동 작업 진행중
파이어스토어에서 유저 읽는과정에서 MultipleUserFound 발생하는데 확인 부탁드립니다!
> [feat] add fetching user from Firestore

- teamplan/Sources/Object/Challenge/ChallengeDTO.swift
- teamplan/Sources/Object/Challenge/ChallengeObject.swift
- teamplan/Sources/Object/Log/ChallengeLog.swift
- teamplan/Sources/Services/Challenge/ChallengeManager.swift
- teamplan/Sources/Services/Challenge/ChallengeServicesCoredata.swift
- teamplan/Sources/Services/ChallengeService.swift
- teamplan/Sources/Services/LoginLoadingService.swift
- teamplan/Sources/Services/SignupLoadingService.swift
- teamplan/Sources/Services/Statistics/StatisticsServicesFirestore.swift
* **사용자 상태별 UserDTO 반환로직 단순화**
* **사용자 기록 복원기능 추가**
* 서버기록을 기반으로 로컬정보 업데이트
* 도전과제의 경우, 로그를 기반으로 완료한 도전과제들의 완료상태 변경 및 완료날짜 업데이트 기능추가 
* 자세한 내용은 Commit 메세지 확인 부탁드립니다 :)
> [feat] Refact & Add Feature at 'LoginLoadingService'

- teamplan/Sources/Object/Challenge/ChallengeObject.swift
- teamplan/Sources/Services/Challenge/ChallengeServicesCoredata.swift
- teamplan/Sources/Util/ChallengeIconHelper.swift
- teamplan/Sources/ViewModels/HomeViewModel.swift
- teamplan/Sources/ViewModels/MyChallengeViewModel.swift
- teamplan/Sources/Views/Alert/ChallengeAlertView.swift
- teamplan/Sources/Views/Home/ChallengesView/ChallengesView.swift
- teamplan/Sources/Views/Home/ChallengesView/SubViews/ChallengeCardBackView.swift
- teamplan/Sources/Views/Home/ChallengesView/SubViews/ChallengeDetailView.swift
- teamplan/Sources/Views/Home/HomeView.swift
- teamplan/Sources/Views/Home/MainTapView.swift
1. 도전과제 도전하기 기능 추가
2. 얼럿뷰 분기처리
3. 도전과제 포기하기
> [feat] Refact & Add Feature at 'ChallengeAlertView'

- teamplan/Sources/Object/Challenge/ChallengeDTO.swift
- teamplan/Sources/Object/Challenge/ChallengeObject.swift
- teamplan/Sources/Services/ChallengeService.swift
- teamplan/Sources/ViewModels/HomeViewModel.swift
- teamplan/Sources/Views/Alert/ChallengeAlertView.swift
- teamplan/Sources/Views/Home/ChallengesView/ChallengesView.swift
- teamplan/Sources/Views/Home/ChallengesView/SubViews/ChallengeCardFrontView.swift
- teamplan/Sources/Views/Home/HomeView.swift
1. 포기하기 버튼 클릭시 에러 수정
2. 뷰모델 데이터 바인딩 구조 변경
3. 나의 도전과제, 모든 도전과제 데이터 변경 시 나의 도전과제에 뒤집혔던 카드뷰 원복
> [fix] fix bug in challengesView

- teamplan/Resources/Storage/Coredata.xcdatamodeld/Coredata.xcdatamodel/contents
- teamplan/Sources/Object/Project/ProjectDTO.swift
- teamplan/Sources/Object/Project/ProjectObject.swift
- teamplan/Sources/Object/Project/TodoDTO.swift
- teamplan/Sources/Object/Project/TodoObject.swift
- teamplan/Sources/Object/Statistics/StatisticsDTO.swift
- teamplan/Sources/Object/Statistics/StatisticsObject.swift
- teamplan/Sources/Services/HomeService.swift
- teamplan/Sources/Services/Project/ProjectServicesCoredata.swift
- teamplan/Sources/Services/Project/TodoServicesCoredata.swift
- teamplan/Sources/Services/ProjectDetailService.swift
- teamplan/Sources/Services/ProjectIndexService.swift
- teamplan/Sources/Services/Statistics/StatisticsServicesCoredata.swift
- teamplan/Sources/Util/Utilities.swift
* **ProjectDetailService 추가**
* 프로젝트 상세페이지 기능함수 모음
* Todo 관련 기능집중
* 프로젝트 완료 시 기능은 개발예정
* **Statistics**
* ProjectDetailService 관련 DTO 생성
* 전체적인 코드 스타일링 진행
* **Etc**
* 주석조정 및 서포트함수 추가    
자세한 내용은 Commit 메세지 확인 부탁드립니다 :)
> [feat] Add 'ProjectDetailService' and Support Function

- teamplan/Sources/Object/Log/ChallengeLog.swift
- teamplan/Sources/Object/Statistics/StatisticsObject.swift
- teamplan/Sources/Object/User/UserDTO.swift
- teamplan/Sources/Object/User/UserObject.swift
- teamplan/Sources/Services/ChallengeService.swift
- teamplan/Sources/Services/HomeService.swift
- teamplan/Sources/Services/Log/LogManager.swift
- teamplan/Sources/Services/Login/SynchronizeLocal.swift
- teamplan/Sources/Services/Login/SynchronizeServer.swift
- teamplan/Sources/Services/LoginLoadingService.swift
- teamplan/Sources/Services/User/UserServicesCoredata.swift
- teamplan/Sources/Util/Utilities.swift
* **로그기능 추가**
* 로그인까지 진행과정을 print로 로그화
* 로깅기능을 Utilities 에 함수화
* **리팩토링**
* 로그인 로딩관련 로깅포인트 추가
* 동기화 파트에 롤백부분 추가
* 로그매니저 개편 
자세한 내용은 Commit 메세지 확인 부탁드립니다 👍
> [feat] Add Logging Function & refactoring

- teamplan/Sources/Services/ChallengeService.swift
- teamplan/Sources/Services/Log/LogManager.swift
- teamplan/Sources/Services/Login/SynchronizeLocal.swift
- teamplan/Sources/Services/LoginLoadingService.swift
- teamplan/Sources/Services/SignupLoadingService.swift
* **SignupLoadingService**
* Executor 동작간 로깅포인트 추가
* **LogManager**
* 상위 호출자를 표기하는 로그변수 추가
자세한 변경내용은 Commit 메세지 확인 부탁드립니다!
> [feat] Add logging point at 'SignupLoadingService' & add new log parameter at 'LogManager'

- teamplan/Sources/Object/Authentication/AuthDTO.swift
- teamplan/Sources/Object/Challenge/ChallengeDTO.swift
- teamplan/Sources/Services/ChallengeService.swift
- teamplan/Sources/Services/Log/LogManager.swift
- teamplan/Sources/Services/Login/AuthGoogleServices.swift
- teamplan/Sources/Services/Login/SynchronizeLocal.swift
- teamplan/Sources/Services/LoginService.swift
- teamplan/Sources/ViewModels/AuthenticationViewModel.swift
- teamplan/Sources/Views/Authentication/LoginView.swift
* **ChallengeService**
* 전체적인 코드 재구성
* 복잡한 사용 설명서 제거
* 서비스 핵심 함수들은 'MyChallenge' & 'Challenge' Main 파트로 구분
* **LocalSynchronizer**
* 완료한 도전과제 복구기능 고도화
* 다음 도전과제 잠금해제 기능추가
자세한 내용은 commit 메세지 참조 부탁드려요!
> [update] Rework 'ChallengeService' & challenge related in 'LocalSynchronizer'

- teamplan/Sources/Services/ChallengeService.swift
- teamplan/Sources/Services/HomeService.swift
- teamplan/Sources/Services/LoginLoadingService.swift
- teamplan/Sources/Services/SignupLoadingService.swift
- teamplan/Sources/Services/Synchronize/SyncLocaltoServer.swift
- teamplan/Sources/Services/Synchronize/SyncServerToLocal.swift
* 동기화 클래스를 위한 신규그룹생성
* 주요함수 및 핵심 기능함수에 주석추가
* 다기능 'PageService' 에서 사용중인 변수들의 'private' 전환
자세한 내용은 Commit 메세지 및 Xcode 주석참조 기능으로 확인 부탁드립니다!
> [Update] Add description & code repositioning at Service

- teamplan/Resources/Storage/Coredata.xcdatamodeld/Coredata.xcdatamodel/contents
- teamplan/Sources/Object/ChallengeObject.swift
- teamplan/Sources/Object/StatisticsObject.swift
- teamplan/Sources/Protocol/CoreDataManaging.swift
- teamplan/Sources/Protocol/FireStoreManaging.swift
- teamplan/Sources/Services/Challenge/ChallengeServicesCoredata.swift
- teamplan/Sources/Services/Challenge/ChallengeServicesFirestore.swift
- teamplan/Sources/Services/ChallengeService.swift
- teamplan/Sources/Services/CoreValue/CoreValueServicesCoredata.swift
- teamplan/Sources/Services/HomeService.swift
- teamplan/Sources/Services/Log/AccessLogServicesCoredata.swift
- teamplan/Sources/Services/LoginLoadingService.swift
- teamplan/Sources/Services/MypageService.swift
- teamplan/Sources/Services/Project/ProjectServicesCoredata.swift
- teamplan/Sources/Services/Project/TodoServicesCoredata.swift
- teamplan/Sources/Services/ProjectService.swift
- teamplan/Sources/Services/SignupLoadingService.swift
- teamplan/Sources/Services/Statistics/StatisticsServicesCoredata.swift
- teamplan/Sources/Services/Synchronize/SyncLocalWithServer.swift
- teamplan/Sources/Services/Synchronize/SyncServerWithLocal.swift
- teamplan/Sources/Services/User/UserServicesCoredata.swift
- teamplan/Sources/Util/Utilities.swift
- teamplan/Sources/ViewModels/HomeViewModel.swift
- teamplan/Sources/Views/Home/HomeView.swift
* **Coredata 관련이슈 해결**
* #91 
* **ChallengeService 개편**
* View/VewModel 에서의 활용성 증대를 위해 ProjectService 방식으로 개편 
* **ProjectService BugFix**
* 목표정렬 기능추가
* 등록가능한 Todo개수 정상표기
* **LoginLoadingService**
* 로컬데이터 확인로직 개선
* **MypageService**
* 마이페이지 기능코드 추가  
자세한 내용은 commit 메세지 확인 부탁드립니다!
(ChallengeService 의 경우 모든 정보를 다 활용하기 위해서는 View/ViewModel 단에서 사용객체 변경이 필요합니다)
> [refact][feat] Service BugFix update & Add MypageService

- teamplan/Sources/Extensions/View+Extension.swift
- teamplan/Sources/ViewModels/ProjectViewModel.swift
- teamplan/Sources/Views/Alert/ProjectCompleteAlertModifier.swift
- teamplan/Sources/Views/Alert/ProjectCompleteAlertView.swift
- teamplan/Sources/Views/Project/AddProjectView.swift
- teamplan/Sources/Views/Project/ProjectDetailView.swift
- teamplan/Sources/Views/Project/ProjectMainView.swift
- teamplan/Sources/Views/Project/SubViews/ProjectCardView.swift
- 프로젝트, 투두, 스탯 데이터 뷰 바인딩
- 프로젝트 추가
- 프로젝트 삭제
- 프로젝트 완료
- 투두 추가 및 수정
> [Feat] Add Project features

- teamplan/Info.plist
- teamplan/Sources/App/TeamPlanApp.swift
- teamplan/Sources/Protocol/CoreDataManaging.swift
- teamplan/Sources/Services/Project/ProjectServicesBackground.swift
- teamplan/Sources/Services/Project/ProjectServicesCoredata.swift
- teamplan/teamplan.entitlements
* **Coredata**
- Status 가 'ongoing' 이거나 'complete' 인 project 데이터를 fetch하는 함수추가
- 관련 Protocol 및 기능코드 추가
* **Service**
- Fetch한 project 데이터의 주요시점을 연산하는 함수추가
- 주요시점은 전체기간의 1/2, 3/4, 마감일 하루전으로 설정
- 해당되는 project 개수를 카운트한 다음, 알림메세지 구성
* **App Delegate**
- 알림권한을 요청하는 함수추가
- 스케쥴러에 백그라운드 동작을 추가하는 함수추가
- 오전 9시에 로컬 푸쉬알람을 스케쥴링하는 함수추가
- 백그라운드 동작이 완료된 후, 다음날 0시에 백그라운드 함수가 동작되도록 스케쥴링하는 함수추가
* Etc
- 백그라운드 동작과 로컬알림이 동작되도록 info.plist & teamplan.entitlement 파일변경  
확인 부탁드립니다!
> [feat] Add Background Task

- teamplan/Sources/Services/HomeService.swift
- teamplan/Sources/ViewModels/HomeViewModel.swift
- teamplan/Sources/Views/Home/ChallengesView/ChallengesView.swift
1. 도전과제 데이터 바인딩 수정
2. 불필요한 코드 삭제
> [Refact] Use userData in homeViewModel for ChallengesView

- teamplan/Sources/Object/ProjectObject.swift
- teamplan/Sources/ViewModels/HomeViewModel.swift
- teamplan/Sources/ViewModels/MypageViewModel.swift
- teamplan/Sources/Views/Home/HomeView.swift
- teamplan/Sources/Views/Home/SubView/MyProjectView.swift
1. MyProjectView가 MyProjectCardView로 덮어씌워진 문제 해결
> fix - merge conflict MyProjectView

- teamplan/Sources/Protocol/CoreDataManaging.swift
- teamplan/Sources/Repository/Challenge/ChallengeServicesCoredata.swift
- teamplan/Sources/Repository/CoreValue/CoreValueServicesCoredata.swift
- teamplan/Sources/Repository/Log/Access/AccessLogServicesCoredata.swift
- teamplan/Sources/Repository/Log/ProjectExtend/ProjectExtendLogServicesCoredata.swift
- teamplan/Sources/Repository/Project/ProjectServicesCoredata.swift
- teamplan/Sources/Repository/Project/TodoServicesCoredata.swift
- teamplan/Sources/Repository/Statistics/StatisticsServicesCoredata.swift
- teamplan/Sources/Repository/User/UserServicesCoredata.swift
- teamplan/Sources/Services/HomeService.swift
- teamplan/Sources/Services/Login/LoginLoadingService.swift
- teamplan/Sources/Services/Login/LoginService.swift
- teamplan/Sources/Services/Login/Synchronize/DeleteSynchronize.swift
- teamplan/Sources/Services/Login/Synchronize/LocalSynchronize.swift
- teamplan/Sources/Services/Login/Synchronize/ServerSynchronize.swift
- teamplan/Sources/Services/MypageService.swift
- teamplan/Sources/Services/ProjectService.swift
- teamplan/Sources/Services/Signup/SignupLoadingService.swift
- teamplan/Sources/Util/LocalStorageManager.swift
- teamplan/Sources/Util/NetworkManager.swift
- teamplan/Sources/Util/UserDefaultManager.swift
- teamplan/Sources/ViewModels/AuthenticationViewModel.swift
- teamplan/Sources/ViewModels/MypageViewModel.swift
- teamplan/Sources/Views/Authentication/LoginView.swift
- teamplan/Sources/Views/Home/HomeView.swift
- teamplan/Sources/Views/Signup/SignupView.swift
* Coredata
- 객체별 Set 과정중 nil 데이터 확인로직 추가
- 배열 데이터를 get or delete 객체에 대해서 빈 배열일 경우, 조기종료 로직추가
* 회원가입
- local storage(Coredata) set 로직강화
* 로그인
- FirebaseAuth 에는 등록되어 있으나, Server 에 저장정보가 없는 사용자 처리로직 추가
: 회원가입 중 앱종료, 혹은 회원가입 취소 사용자 대상
: 진행된 과정 초기화 및 FirebaseAuth 등록유저 제거
* LoginService
- 분산되어있는 로그아웃 및 회원탈퇴 코드를 이곳에 배치
* Etc
- NetworkManager 동작방식 변경
- 일부 View 내 'showAlert' 변수명 변경
- 일부 부정확한 Error 관련 print 로그명 변경
* 로그인 후, HomeView 진입 시 Layout Constraints 문제가 오류메세지로 등장하고 있습니다!
```
2024-07-09 18:40:40.457799+0900 투두팡[9182:338091] [LayoutConstraints] Unable to simultaneously satisfy constraints.
Probably at least one of the constraints in the following list is one you don't want. 
Try this: 
(1) look at each constraint and try to figure out which you don't expect; 
(2) find the code that added the …
```
> [refact][feat] 20240709_Patch_Note

- teamplan/Sources/Services/ProjectService.swift
* ProjectService
- Todo 상태값 변경불가 오류해결 
- Object에 값 변경이 제대로 진행되지 않아 이슈발생
- Todo 정렬함수 추가
- 상태값 및 등록ID 값과 상태값에 따른 Todo 정렬함수 추가
확인 부탁드립니다 :)
> [refact][feat] 20240717_Patch_Note

- teamplan/Sources/ViewModels/AuthenticationViewModel.swift
- teamplan/Sources/Views/Authentication/LoginView.swift
* appleSocialLogin 진행 시, FirebaseAuth에 등록되지 않는 문제확인
* encoded 된 nonce 가 아닌, raw nonce 가 저장되도록 로직수정
애플 소셜로그인 불가문제로 급하게 올린 패치입니다..!
> [debug] 20240718 HotFix about appleSocialLogin

- teamplan/Sources/Services/ChallengeService.swift
- teamplan/Sources/ViewModels/ChallengeViewModel.swift
- teamplan/Sources/Views/Challenges/ChallengesView.swift
* 도전과제쪽 들어가면서 강제종료되는 버그 수정
* 도전과제 순서가 랜덤으로 나옴 -> 정렬을 ID순으로
* 도전과제 클릭시 나오는 얼럿 아이콘 수정
> [Fix] fixed Challenge View bugs

- teamplan/Sources/Services/ProjectService.swift
- teamplan/Sources/ViewModels/ProjectViewModel.swift
- teamplan/Sources/Views/Alert/ChallengeAlertView.swift
- teamplan/Sources/Views/Challenges/ChallengesView.swift
- teamplan/Sources/Views/Challenges/SubViews/ChallengeCardBackView.swift
- teamplan/Sources/Views/Home/NotificationView/NotificationEmptyView.swift
- teamplan/Sources/Views/Home/NotificationView/NotificationView.swift
- teamplan/Sources/Views/Home/SubView/MyProjectView.swift
- teamplan/Sources/Views/MyPage/MyPageView.swift
- teamplan/Sources/Views/Onboarding/IntroView.swift
* 안쓰는 print문 삭제
* 프로젝트 데이터 뷰모델에서 구독처리
* 마이페이지 내 탈퇴, 로그아웃 메뉴 삭제
* 알림 화면에서 알림 없을 경우 안내 문구 추가
> [refact] remove unnecessary features

- teamplan/Sources/Repository/Project/ProjectServicesCoredata.swift
- teamplan/Sources/Services/Authentication/LoginService.swift
- teamplan/Sources/Services/ChallengeService.swift
- teamplan/Sources/Services/Notification/LiteNotifyService.swift
- teamplan/Sources/Services/Notification/NotificationService.swift
- teamplan/Sources/Services/ProjectService.swift
- teamplan/Sources/Util/ChallengeNotifyManager.swift
- teamplan/Sources/ViewModels/ChallengeViewModel.swift
- teamplan/Sources/ViewModels/NotificationViewModel.swift
- teamplan/Sources/Views/Alert/ChallengeAlertView.swift
- teamplan/Sources/Views/Challenges/ChallengesView.swift
- teamplan/Sources/Views/Project/AddProjectView.swift
- teamplan/Sources/Views/Project/ProjectDetailView.swift
- teamplan/Sources/Views/Project/ProjectMainView.swift
* 도전과제(Challenge) 관련 버그픽스
* AlertView 표기 데이터 및 Grid 출력 관련
* 알람(Notify) 관련 버그픽스
* 중복데이터 처리 및 사용자 동작 시, 알람생성 관련    
자세한 내용은 Commit 메세지 확인 부탁드립니다!
> [BugFix] Challenge & Notify

- teamplan/Sources/Views/Project/SubViews/ToDoView.swift
> [Fix] fixed todoView textField

- teamplan/Sources/Services/MypageService.swift
- teamplan/Sources/ViewModels/MypageViewModel.swift
- teamplan/Sources/Views/Home/SubView/MyProjectCardView.swift
- teamplan/Sources/Views/MyPage/MyPageView.swift
* 테스트를 위한 MockData 생성기 제거
* 기능 제거에 따른 연관코드 수정
자세한 내용은 코드확인 부탁드립니다 :)
> [refact] Renew MyPage
